### ISSUE TITLE
Not 107 bytes

### ISSUE THREAD

**Issue by Morglod** [ai/nanoevents#70]
Hi! Its actually not 107 bytes! Minimum I measured was 138.

```
// using minified-size

"originalSize": 419,
"minifiedSize": 219,
"gzippedSize": 167,
"brotliedSize": 138
```

**Comment by ai** [comment]
It depends from the measurements method.

We use Size Limit tool, which use “adding price” method. It creates new empty esbuild project, remembers it's size before, adds Nano ID, Ana check the size after. 

https://github.com/ai/size-limit/

We think this method is better, because it tells you how your JS bundle size will change after adding Nano ID.

**Comment by Morglod** [comment]
It has terribly wrong calculations inside
(eg for 89 bytes js it says that package size is 331 bytes) (4 times bigger)

Which is impossible

**Comment by ai** [comment]
> (eg for 89 bytes js it says that package size is 331 bytes) (4 times bigger)

Feel free to open an issue in Size Limit with JS input details. I will look. It should not be like this. 

One of possible reasons is that esbuild adds some polyfill which increases the size (so affect on the real cost).
